config/routes.rb
Rails.application.routes.draw do
  post '/hooks/webflow', to: 'webflow_webhook#webflow_webhook'

  get '/tests/registration', to: 'tests#new_registration'
  post '/tests/registration', to: 'tests#register'

  get '/longest_lab_name', to: 'labs#longest_lab_name'

  resources :users do
    post :deactivate, on: :member
  end

  resources :companies, :labs
  resources :tests, only: [:show, :destroy]
  resources :company_lab_connections, except: [:show]

  resources :users do
    resources :tests, except: [:edit]
  end
  
  namespace :admin do 
    resources :tests
    resources :users, except: [:edit, :update]
    resources :users do
      resources :tests, only: [:create]
    end
  end


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  
  root 'sessions#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin/navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Home", root_path, class: "logo sml" %>
  </div>
  <div class="nav-links-container">
    <%= link_to "My Profile", admin_user_path(current_user), class: "navbar-item" if logged_in? %>
    <%= link_to "New Test", new_admin_test_path, class: "navbar-item" if logged_in? && company_admin? %>
    <%= link_to "All Tests", admin_tests_path, class: "navbar-item" if logged_in? %>
    <%= link_to "Log Out", logout_path, method: 'delete', class: "btn primary-outline" if logged_in? %>
  </div>
</nav>