config/routes.rb
Rails.application.routes.draw do
  post '/hooks/webflow', to: 'webflow_webhook#webflow_webhook'

  get '/tests/registration', to: 'tests#new_registration'
  post '/tests/registration', to: 'tests#register'

  get '/longest_lab_name', to: 'labs#longest_lab_name'

  resources :users do
    post :deactivate, on: :member
  end

  resources :companies, :labs
  resources :tests, only: [:show, :destroy]
  resources :company_lab_connections, except: [:show]

  resources :users do
    resources :tests, except: [:edit]
  end
  
  namespace :admin do 
    resources :tests
    resources :users, except: [:edit, :update]
    resources :users do
      resources :tests, only: [:create]
    end
  end


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  
  root 'sessions#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :tests

    belongs_to :company, optional: true
    belongs_to :lab, optional: true
    
    validates :first_name, :last_name, :email, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

    scope :is_customer, -> {where(is_customer: true)}
    scope :belong_to_company, -> {where(belongs_to_company: true)}
    scope :of_current_company, -> (company) {where("company_id = ?", company)}



    def self.create_from_omniauth(auth)
        self.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.first_name = auth[:info][:first_name]
            u.last_name = auth[:info][:last_name]
            u.email = auth[:info][:email]
            u.is_customer = true
            u.password = SecureRandom.hex(16)
        end
    end

    def self.create_from_omniauth_lab(auth)
        self.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            lab = Lab.new(name: SecureRandom.hex(5))
            lab.users << u
            u.first_name = auth[:info][:first_name]
            u.last_name = auth[:info][:last_name]
            u.email = auth[:info][:email]
            u.belongs_to_lab = true
            u.lab_super_admin = true
            u.password = SecureRandom.hex(16)
        end
    end
    def self.create_from_omniauth_company(auth)
        self.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            company = Company.new(name: SecureRandom.hex(5))
            company.users << u
            u.first_name = auth[:info][:first_name]
            u.last_name = auth[:info][:last_name]
            u.email = auth[:info][:email]
            u.belongs_to_company = true
            u.super_admin = true
            u.password = SecureRandom.hex(16)
        end
    end

    def self.send_welcome_email(user)
        if user.created_at.utc + 1.minutes > Time.now.utc
            UserMailer.welcome_email(user).deliver_later
        end
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :require_login
    before_action :is_admin_user, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.company = current_company
        @user.belongs_to_company = true
        if @user.save
            redirect_to company_path(current_user)
        else
            render 'new'
        end
    end

    def index
        @users = current_company.company_customers(current_company)
    end

    def show
        find_user
    end
    
    def edit
    end

    def update
    end

    def destroy
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, except: [:new, :create]
    before_action :only_user_can_view, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        set_customer_permissions
        if @user.save
            # UserMailer.welcome_email(@user).deliver_now
            set_user
            redirect_to @user
        else
            render 'new'
        end

    end

    def show
        binding.pry
    end

    def edit
        find_user
    end

    def update
        find_user
        @user.update(user_params)
        redirect_to @user, notice: "Profile Updated"
    end

    def deactivate
        find_user.active = false
        redirect_to root_path
    end
    
    def destroy
        find_user.delete 
        session[:user_id] = nil
        redirect_to root_path
    end

    private 

    def user_params
        params.require(:user).permit(:first_name, :last_name, :password, :email, :birthdate, :gender, :phone, :dr_email)
    end

    def set_customer_permissions
        @user.is_customer = true
    end

end

app/helpers/users_helper.rb
module UsersHelper

    def only_user_can_view
        redirect_to root_path, notice: "Restricted" unless logged_in? && current_user.id == params_id_integer
    end

    def user_can_view_user
        redirect_to root_path, notice: "Restricted" unless logged_in? && current_user.is_customer && current_user.id == params[:user_id].to_i || current_user.super_admin && current_user.company.company_customers(current_company).include?(User.find(params[:user_id] ))
    end

    def is_admin_user
        redirect_to root_path, notice: "Restricted" unless logged_in? && current_user.id == params_id_integer && current_user.belongs_to_company || current_user.belongs_to_lab
    end

    def customer_has_provided_all_info
        current_user.first_name != nil && current_user.last_name != nil && current_user.email != nil && current_user.birthdate != nil && current_user.gender!= nil && current_user.phone != nil
    end

    def is_customer?
        current_user.is_customer
    end

    def has_access_to_company_tests?
        redirect_to user_path(current_user), notice: "Restricted" unless logged_in? && current_user.super_admin || current_user.belongs_to_company || current_user.lab_super_admin
    end

    def can_delete_tests?
        redirect_to user_path(current_user), notice: "Restricted" unless logged_in? && current_user.super_admin
    end

    def redirect_unless_company_super_admin?
        redirect_to user_path(current_user), notice: "Restricted" unless logged_in? && current_user.super_admin 
    end

    def redirect_unless_lab_super_admin?
        redirect_to user_path(current_user), notice: "Restricted" unless logged_in? && current_user.lab_super_admin
    end

    def is_admin?
        redirect_to user_path(current_user), notice: "Restricted" unless logged_in? && current_user.super_admin || current_user.lab_super_admin
    end

    def is_signup_or_create_page
        params[:action] == "new" || params[:action] == "create"
    end

    def is_edit_or_update_page
        params[:action] == "edit" || params[:action] == "update"
    end
end

app/views/users/_base_user_form.html.erb
<%= f.label :first_name, class: "label" %>
<%= f.text_field :first_name, class: input_with_errors_class(@user, :first_name) %>
<p class="help is-danger"><%= format_error(@user.errors[:first_name]) if @user.errors.any? %></p>

<%= f.label :last_name, class: "label" %>
<%= f.text_field :last_name, class: input_with_errors_class(@user, :last_name) %> 
<p class="help is-danger"><%= format_error(@user.errors[:last_name]) if @user.errors.any? %></p>

<%= f.label :email, class: "label" %>
<%= f.text_field :email, class: input_with_errors_class(@user, :email) %> 
<p class="help is-danger"><%= format_error(@user.errors[:email]) if @user.errors.any? %></p>

<% if !logged_in? || is_signup_or_create_page %>
    <%= f.label :password, class: "label" %>
    <%= f.password_field :password, class: input_with_errors_class(@user, :password) %>
    <p class="help is-danger"><%= format_error(@user.errors[:password]) if @user.errors.any? %></p>
<% end %>

app/views/users/_company_dashboard.html.erb
  <p class="menu-label">
      Admin
  </p>
  <ul class="menu-list">
    <li><%= link_to "Add Lab", new_company_lab_connection_path %></li>
    <li><%= link_to "Add Admin", new_admin_user_path %></li>
    <li><%= link_to "Lab Connections", company_lab_connections_path %></li>
    <li><%= link_to "Company", company_path(current_company) %></li>
    <li><%= link_to "Edit Company", edit_company_path(current_company) %></li>
  </ul>
  <p class="menu-label">
      Tests
  </p>
  <ul class="menu-list">
    <li><%= link_to "All Tests", admin_tests_path %></li>
    <li><%= link_to "New Test", new_admin_test_path %></li>
  </ul>
  <p class="menu-label">
    Profile
  </p>
  <ul class="menu-list">
    <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
  </ul>

app/views/users/_dashboard.html.erb
<div class="container">
  <div class="container-box">
    <h1>Welcome <%= current_user.first_name%></h1>
    <div class="divider"></div>
    <aside>
      <%= render 'users/company_dashboard' if current_company %>
      <%= render 'users/lab_dashboard' if current_lab %>
      <%= render 'users/user_dashboard' if current_user && current_user.is_customer %>
      <div class="divider"></div>
      <!-- this is the delete account button -->
      <!-- <%#= button_to "Delete Account", user_path, method: "delete", class: "btn-sm red-outline", data: { confirm: 'Are you sure you want to delete your account? This action can not be undone.' } %> -->
    </aside>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user, html: {class:"form-stretch"} do |f| %>
        <%= f.label :first_name, class: "label" %>
        <%= f.text_field :first_name, class: input_with_errors_class(@user, :first_name) %>
        <p class="help is-danger"><%= format_error(@user.errors[:first_name]) if @user.errors.any? %></p>

        <%= f.label :last_name, class: "label" %>
        <%= f.text_field :last_name, class: input_with_errors_class(@user, :last_name)  %>
        <p class="help is-danger"><%= format_error(@user.errors[:last_name]) if @user.errors.any? %></p>

        <%= f.label :email, class: "label" %>
        <%= f.text_field :email, class: input_with_errors_class(@user, :email)  %>
        <p class="help is-danger"><%= format_error(@user.errors[:email]) if @user.errors.any? %></p>

        <%= f.label :birthdate, class: "label" %>
        <%= f.text_field :birthdate, placeholder: "mm/dd/yyyy", type: "date", class: input_with_errors_class(@user, :birthdate)  %>
        <p class="help is-danger"><%= format_error(@user.errors[:birthdate]) if @user.errors.any? %></p>

        <%= f.label :gender, class: "label"%>
        <div class="input-box">
            <%= f.select :gender, ['Male', 'Female', 'Prefer not to say', 'Other'], :prompt => 'Select Gender', class: input_with_errors_class(@user, :gender)  %>
        </div> 
        <p class="help is-danger"><%= format_error(@user.errors[:gender]) if @user.errors.any? %></p>

        <%= f.label :phone, class: "label" %>
        <%= f.text_field :phone, class: input_with_errors_class(@user, :phone)  %> 
        <p class="help is-danger"><%= format_error(@user.errors[:gender]) if @user.errors.any? %></p>

        <%= f.label :dr_email, class: "label" %>
        <%= f.text_field :dr_email, class: input_with_errors_class(@user, :dr_email) %> 
        <p class="help is-danger"><%= format_error(@user.errors[:dr_email]) if @user.errors.any? %></p>
        <% if !logged_in? %>
            <%= f.label :password, class: "label" %>
            <%= f.password_field :password, class: input_with_errors_class(@user, :password) %>
            <p class="help is-danger"><%= format_error(@user.errors[:password]) if @user.errors.any? %></p>
        <% end %>
        <%= f.submit "Sign Up", class: "btn" if is_signup_or_create_page %>
        <%= f.submit "Save Changes", class: "btn" if is_edit_or_update_page %>
        
<% end %>

app/views/users/_lab_dashboard.html.erb
<%= render 'company_lab_connections/pending_connections' if current_user.lab_super_admin %>
<p class="menu-label">
    Admin
</p>
<ul class="menu-list">
  <li><%= link_to "Company Connections", company_lab_connections_path %></li>
  <li><%= link_to "Edit Lab", edit_lab_path(current_lab) %></li>
</ul>
<p class="menu-label">
    Tests
</p>
<ul class="menu-list">
  <li><%= link_to "All Tests", admin_tests_path %></li>
</ul>
<p class="menu-label">
  Profile
</p>
<ul class="menu-list">
  <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
</ul>

app/views/users/_user_dashboard.html.erb
    <p class="menu-label">
      tests
    </p>
    <ul class="menu-list">
      <li><%= link_to "My Tests", user_tests_path(current_user) %></li>
      <li><%= link_to "Test Registration", tests_registration_path %></li>
    </ul>
    <p class="menu-label">
      Profile
    </p>
    <ul class="menu-list">
      <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
    </ul>

app/views/users/edit.html.erb
<div class="container">
    <div class="container-box auto-grid-rows max-w-five">
        <%= render 'form' %>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="container-box auto-grid-rows max-w-five">
        <%= render 'form' %>
        <%= render 'sessions/google_auth/google_button' %>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'dashboard' %>