config/routes.rb
Rails.application.routes.draw do
  post '/hooks/webflow', to: 'webflow_webhook#webflow_webhook'

  get '/tests/registration', to: 'tests#new_registration'
  post '/tests/registration', to: 'tests#register'

  get '/longest_lab_name', to: 'labs#longest_lab_name'

  resources :users do
    post :deactivate, on: :member
  end

  resources :companies, :labs
  resources :tests, only: [:show, :destroy]
  resources :company_lab_connections, except: [:show]

  resources :users do
    resources :tests, except: [:edit]
  end
  
  namespace :admin do 
    resources :tests
    resources :users, except: [:edit, :update]
    resources :users do
      resources :tests, only: [:create]
    end
  end


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  
  root 'sessions#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company_lab_connection.rb
class CompanyLabConnection < ApplicationRecord
    belongs_to :company 
    belongs_to :lab, optional: true

    scope :pending_company_lab_connections, -> {where("pending = true")}

    def self.current_company_lab_connections(entity)
        entity.company_lab_connections.where(accepted: true)
    end
end

app/controllers/company_lab_connections_controller.rb
class CompanyLabConnectionsController < ApplicationController
    before_action :require_login, :is_admin?
    before_action :redirect_unless_company_super_admin?, only: [:new]

    def new
        @company_lab_connection = CompanyLabConnection.new
        @user = User.new # email used to find and associate company and lab
    end
    
    def create
        @company_lab_connection = CompanyLabConnection.new
        if user = User.find_by(email: company_lab_connection_params[:user][:email])
            @company_lab_connection.company = current_company
            @company_lab_connection.lab = user.lab
            @company_lab_connection.pending = true
            @company_lab_connection.save
            redirect_to admin_user_path(current_user), notice: "Connection Pending"
        else
            redirect_to admin_user_path(current_user), notice: "Unable to connect"
        end
    end

    def index
        if !current_lab.nil?
            @company_lab_connections = CompanyLabConnection.current_company_lab_connections(current_lab)
        elsif !current_company.nil?
            @company_lab_connections = CompanyLabConnection.current_company_lab_connections(current_company)
        end
        if @company_lab_connections.empty?
            flash[:message] = "No connections yet."
        end
    end

    def edit
        @user = User.find_by(id: params[:id])
    end

    def update
        connection = find_company_lab_connection
        update_connection_status_sucessful
        if @company_lab_connection.save
            redirect_to admin_user_path(current_user), notice: "Connection succesful"
        else
            redirect_to admin_user_path(current_user), notice: "Unable to connect"
        end
    end
    
    def destroy
        find_company_lab_connection.destroy
        redirect_to current_user
    end
    

    private 

    def company_lab_connection_params
        params.require(:company_lab_connection).permit(user: [
            :email
        ])
    end

    def find_company_lab_connection
        @company_lab_connection = CompanyLabConnection.find_by(id: params[:id])
    end

    def update_connection_status_sucessful
        @company_lab_connection.pending = false
        @company_lab_connection.accepted = true
        @company_lab_connection.completed = true
    end

end

app/helpers/company_lab_connections_helper.rb
module CompanyLabConnectionsHelper

    def pending_lab_connections
        current_lab.company_lab_connections.where(pending: true)
    end
end

app/views/company_lab_connections/_form.html.erb
<%= form_for @company_lab_connection, html: {class:"form-stretch"} do |f| %>

    <%= f.fields_for @user do |user_form| %>
        <%= user_form.label :email, class: "label" %>
        <%= user_form.text_field :email, class: input_with_errors_class(@user, :email) %>
        <p class="help is-danger"><%= format_error(@user.errors[:email]) if @user.errors.any? %></p>
    <% end %>
    
    <%= f.submit "Connect Lab", class: "btn" %>
<% end %>

app/views/company_lab_connections/_pending_connections.html.erb
<% pending_lab_connections.each do |connection| %>
    <div class="notification is-link is-light">
        <button class="delete"></button>
        <strong><%= connection.company.name %></strong> wants to connect. <br></br>
        <%= link_to "accept", company_lab_connection_path(connection), method: :patch, class: 'button is-small is-link' %> 
        <%= link_to "decline", company_lab_connection_path(connection), method: :delete, class: 'button is-small is-danger' %>
      </div>
<% end %>

app/views/company_lab_connections/index.html.erb
<div class="container">
  <div class="grid four-column margin-top margin-bottom">
    <% @company_lab_connections.each do |connection| %>
      <div class="container-box margin-bottom">
        <div>
          <% if current_lab %>
            <%= connection.company.name %>
          <% elsif current_company %>
            <%= connection.lab.name %>
          <% end %>
        </div>
        
        <time datetime="2016-1-1" class="info-text">Connected on <%= readable_timestamp(connection.created_at) %></time>
        <div class="divider"></div>
        <%= link_to "delete", company_lab_connection_path(connection), class: "btn-sm red-outline", method: 'delete', data: { confirm: 'Are you sure you want to delete your account? This action cannot be undone.' }  if current_user.super_admin %>
    </div>
      <% end %> 
    </div>
  </div>

app/views/company_lab_connections/new.html.erb
<div class="container">
    <div class="container-box auto-grid-rows max-w-five">
        <%= render 'form' %>
    </div>
</div>

app/views/company_lab_connections/show.html.erb
<%= @lab.name %>