config/routes.rb
Rails.application.routes.draw do
  post '/hooks/webflow', to: 'webflow_webhook#webflow_webhook'

  get '/tests/registration', to: 'tests#new_registration'
  post '/tests/registration', to: 'tests#register'

  get '/longest_lab_name', to: 'labs#longest_lab_name'

  resources :users do
    post :deactivate, on: :member
  end

  resources :companies, :labs
  resources :tests, only: [:show, :destroy]
  resources :company_lab_connections, except: [:show]

  resources :users do
    resources :tests, except: [:edit]
  end
  
  namespace :admin do 
    resources :tests
    resources :users, except: [:edit, :update]
    resources :users do
      resources :tests, only: [:create]
    end
  end


  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  get '/auth/google_oauth2'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  
  root 'sessions#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% flash.each do |type, msg| %>
    <div class="alert-container ">
        <button class="delete"></button>
        <%= msg  %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>CompanyLabTests</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag :application %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">


    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

    <% if admin? %>
    <%= render template: 'layouts/admin/navbar' %>
    <% else %>
    <%= render template: 'layouts/navbar' %>
    <% end %>

    <%= render 'layouts/alert' %>

    <%= yield %>


    <%= javascript_pack_tag 'all_tests_page_search'%>
</body>

</html>

app/views/layouts/navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to "Home", root_path, class: "logo sml" %>
    </div>
    <div class="nav-links-container">
            <%= link_to "Test Registration", tests_registration_path, class: "tn btn-link" if logged_in? %>
            <%= link_to "My Tests", user_tests_path(current_user), class: "navbar-item" if logged_in? %>
            <%= link_to "My Profile", user_path(current_user), class: "tn btn-link" if logged_in? %>
            <%= link_to "New Company", new_company_path, class: "navbar-item" if !logged_in? %>
            <%= link_to "New Lab", new_lab_path, class: "navbar-item" if !logged_in? %>
            <%= link_to "Login", login_path, class: "is-link" if !logged_in? %>
            <%= link_to "Sign Up", signup_path, class: "btn" if !logged_in? %>
            <%= link_to "Log Out", logout_path, method: 'delete', class: "button is-light" if logged_in? %>
    </div>
  </nav>